#!/usr/bin/env ruby
require "mp3info"
require "optparse"
require "json"
require "ryo"

##
# CLI options
options = Ryo({author: "*"})
OptionParser.new do |o|
  o.on("-aAUTHOR", "--author NAME", "An author's name (default: all authors)")
end.parse(ARGV, into: options)

##
# Paths
root_dir   = File.realpath(File.join(__dir__, "..", ".."))
share_dir  = File.join(root_dir, "share", "quran-audio")
author_dir = File.join(share_dir, options.author)

##
# Utils
def push_timestamp(path, timestamps)
  mp3 = Mp3Info.new(path)
  timestamps.push([
    File.basename(path, File.extname(path)).to_i,
    sprintf("%0.2f", mp3.length).to_f
  ])
ensure
  mp3.close
end

def save_timestamps(path, timestamps)
  File.binwrite(
    File.join(path, "timestamps.json"),
    JSON.dump(timestamps.sort_by(&:first))
  )
end

Dir.glob(File.join(author_dir, "*")).each do |surah_dir|
  timestamps = []
  Dir.glob(File.join(surah_dir, "*.mp3")).each do
    push_timestamp(_1, timestamps)
  end
  save_timestamps(surah_dir, timestamps)
end
