#!/usr/bin/env ruby
# frozen_string_literal: true

lib_dir = File.realpath File.join(__dir__, "..", "..", "lib")
require File.join(lib_dir, "cmd", "extract_slots")

##
# main
def main(argv)
  Cmd::ExtractSlots.new(argv).run
end
main(ARGV)
