#!/usr/bin/env ruby
# frozen_string_literal: true

lib_dir = File.join(__dir__, "..", "..", "lib")
require File.join(lib_dir, "cmd", "pull")

##
# main
def main(argv)
  Cmd::Pull.new(argv).run
end
interrupt = catch(:interrupt) { main(ARGV) }
exit(1) if interrupt
