#!/usr/bin/env ruby
# frozen_string_literal: true

lib_dir = File.realpath File.join(__dir__, "..", "..", "lib", "quran-audio")
require File.join(lib_dir, "time_slot")
require "optparse"
require "fileutils"

##
# main
def main(argv)
  cmd = TimeSlot.new(argv)
  Dir.glob(File.join(cmd.reciter_dir, "[0-9]*")).each do |dir|
    Dir.glob(File.join(dir, "*.mp3")).each { cmd.push(_1) }
    dst_dir = File.join(File.dirname(dir), "time_slots")
    dst_file = File.join(dst_dir, "#{File.basename(dir)}.json")
    FileUtils.mkdir_p(dst_dir)
    cmd.save(dst_file)
    print "Write: #{dst_file.sub(Dir.getwd + "/", "")}", "\n"
  end
end
main(ARGV)
