#!/usr/bin/env ruby
lib_dir = File.realpath File.join(__dir__, "..", "..", "lib", "quran-audio")
require File.join(lib_dir, "timestamps")
require "optparse"

##
# CLI options
options = Ryo({author: "*"})
OptionParser.new do |o|
  o.on("-aAUTHOR", "--author NAME", "An author's name (default: all authors)")
end.parse(ARGV, into: options)

##
# main
def main(options)
  cmd = Timestamps.new(options)
  Dir.glob(File.join(cmd.author_dir, "*")).each do |dir|
    Dir.glob(File.join(dir, "*.mp3")).each do
      cmd.push(_1)
    end
    cmd.save(dir)
  end
end
main(options)
