#!/usr/bin/env ruby
# frozen_string_literal: true

require "tilawah"
require "optparse"

##
# main
def main(argv)
  options = Ryo({})
  option_parser.parse(argv, into: options)
  Tilawah::Command::Ls.new(options).perform
end

##
# utils
def option_parser
  OptionParser.new do |o|
    o.banner = "Usage: tilawah ls [OPTIONS]"
  end
end

excode = catch(:exit) {
  main(ARGV)
  0
}
exit excode
