#!/usr/bin/env ruby
# frozen_string_literal: true

require "tilawah"
require "optparse"

##
# main
def main(argv)
  options = Ryo(bitrate: 128, surahs: (1..114), delay: 0.5)
  option_parser.parse(argv, into: options)
  if argv.empty?
    warn option_parser.help
    throw(:exit, 1)
  else
    Ryo.assign(options, {recitation: argv[0]})
    Tilawah::Command::Pull.new(options).perform
  end
end

##
# utils
def option_parser
  OptionParser.new do |o|
    o.banner = "Usage: tilawah pull [OPTIONS] <RECITER>"
    o.on("-b BITRATE", nil, "MP3 bitrate", Integer)
    o.on("-s NUMBERS", nil, "Comma-separated list of surah IDs", Array)
    o.on("-d SECONDS", nil, "Delay between requests, in seconds", Float)
  end
end

excode = catch(:exit) {
  main(ARGV)
  0
}
exit excode
